[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
ANTHROPIC_AUTH_TOKEN = "sk-69b7982f9ecdd9f9-77ljxa-0c0d35b5"
ANTHROPIC_BASE_URL = "http://localhost:20128/v1"
ANTHROPIC_DEFAULT_HAIKU_MODEL = "cc/claude-haiku-4-5-20251001"
ANTHROPIC_DEFAULT_OPUS_MODEL = "cc/claude-opus-4-5-20251101"
ANTHROPIC_DEFAULT_SONNET_MODEL = "cc/claude-sonnet-4-5-20250929"
API_TIMEOUT_MS = "600000"
